spring.datasource:
  url: jdbc:postgresql://localhost:5432/mydatabase?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: myuser
  password: mypassword
  driver-class-name: org.postgresql.Driver
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect



server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true